<a href="https://colab.research.google.com/github/ankan-git-coder/Deep-learning-COURSE/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


In [9]:
##intro to tensors
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [11]:
MATRIX = torch.tensor([[7, 8],[9, 10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [1,2,3]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [1, 2, 3]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
##RANDOM TENSORS


In [20]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8419, 0.3851, 0.3879, 0.2534],
        [0.6946, 0.5816, 0.6988, 0.1366],
        [0.1990, 0.4322, 0.8653, 0.7523]])

In [21]:

x = torch.randint(low=0, high=10, size=(2, 3))
print(x)


tensor([[1, 3, 9],
        [5, 4, 7]])


In [22]:
random_image_size_tensor = torch.rand(size=(224,224,3))

random_image_size_tensor

tensor([[[0.7088, 0.7016, 0.9543],
         [0.3208, 0.7773, 0.0830],
         [0.7608, 0.4599, 0.9175],
         ...,
         [0.4088, 0.3277, 0.2056],
         [0.1594, 0.5658, 0.9603],
         [0.1867, 0.3445, 0.1470]],

        [[0.8746, 0.1603, 0.9091],
         [0.0377, 0.3098, 0.2571],
         [0.8300, 0.1424, 0.4816],
         ...,
         [0.0210, 0.8023, 0.8382],
         [0.9106, 0.6439, 0.8537],
         [0.5426, 0.2807, 0.9903]],

        [[0.2707, 0.2450, 0.0245],
         [0.1464, 0.1638, 0.6821],
         [0.2899, 0.8624, 0.6149],
         ...,
         [0.0785, 0.6582, 0.2103],
         [0.0540, 0.8040, 0.3041],
         [0.8674, 0.9372, 0.7776]],

        ...,

        [[0.2404, 0.5632, 0.6871],
         [0.8118, 0.2037, 0.9761],
         [0.0354, 0.6032, 0.0977],
         ...,
         [0.1655, 0.6984, 0.3909],
         [0.5354, 0.6609, 0.8845],
         [0.0091, 0.8565, 0.3843]],

        [[0.7611, 0.0095, 0.3906],
         [0.1197, 0.2188, 0.6643],
         [0.

In [23]:
##zeros and ones
zero= torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [27]:
### use torch.arange()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
#creating tensors like


In [29]:
#tensor datatypes
x = torch.tensor([1, 2, 3], dtype=torch.int32)
print(x.dtype)



torch.int32
